version: '3.8'
services:
  django-migrations:
    restart: on-failure
    depends_on:
      - db
    build: .
    command: python manage.py migrate

  django:
    restart: always
    depends_on:
      - django-migrations
    build: .
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: "postgres"
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
    ports:
      - '5432:5432'