version: '3.8'
services:
  django-migrations:
    restart: on-failure
    depends_on:
      - db
    build: .
    command: python manage.py migrate

  django:
    restart: always
    depends_on:
      - django-migrations
    build: .
    command: >
      sh -c "python manage.py loaddata fixtures/*_fixture.json && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: "postgres"
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
      - DB_HOST
    ports:
      - '5432:5432'

  redis:
    image: "redis:latest"
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_CACHE_DB
      - REDIS_CACHE_HOST
      - REDIS_CACHE_PORT
    ports:
      - "6379:6379"
