# Generated by Django 4.2.5 on 2023-10-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_paymentmethod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryoption",
            name="shipment_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
