# Generated by Django 4.2.5 on 2023-10-03 08:25

from django.db import migrations, models
import django.utils.timezone
from django.db import migrations




class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_product_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),

    ]
