# Generated by Django 4.2.5 on 2023-10-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_product_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="<django.db.models.fields.CharField>"),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=models.CharField(max_length=255)),
        ),
    ]
