# Generated by Django 4.2.5 on 2023-10-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_category_slug_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
