# Generated by Django 4.2.5 on 2023-11-20 16:30

from django.db import migrations, models
import src.config.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_fill_product_in_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                storage=src.config.storage_backends.get_public_storage, upload_to="product_images/"
            ),
        ),
    ]
