# Generated by Django 4.2.5 on 2023-09-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_userprofile_alter_user_options_user_user_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("Customer", "Customer"), ("Seller", "Seller"), ("Admin", "Admin")],
                default="Admin",
                max_length=32,
                verbose_name="User type",
            ),
        ),
    ]
