# Generated by Django 4.2.5 on 2023-10-11 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_userprofile_alter_user_options_user_user_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=100)),
                ("building", models.CharField(max_length=10)),
                ("apartment", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mobile_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pictures/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_profile",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="user.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("Customer", "Customer"), ("Seller", "Seller"), ("Admin", "Admin")],
                default="Admin",
                max_length=32,
                verbose_name="User type",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.useraddress",
            ),
        ),
    ]
