# Generated by Django 4.2.5 on 2023-11-20 16:34

import django.core.validators
from django.db import migrations, models
import src.config.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_user_user_type_alter_user_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("Customer", "Customer"), ("Seller", "Seller"), ("Admin", "Admin")],
                default="Admin",
                max_length=32,
                verbose_name="User type",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=src.config.storage_backends.get_private_storage,
                upload_to=src.config.storage_backends.profile_picture_path,
                validators=[django.core.validators.FileExtensionValidator(["jpg", "jpeg", "png"])],
            ),
        ),
    ]
