name: test_awesome_ecommerce
on: [pull_request, push] # activates the workflow when there is a push or pull request in the repo
jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.12
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.1.15
      - name: Install pytest
        run: pip install pytest
      - name: Run pytest report
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          custom-arguments: '-q'
          click-to-expand: true
          report-title: 'Test Report'